- include/settings.h
- src/BLE_Server.cpp
> Moved updateConnParams out of onConnect

- data/hrtowatts.html
- include/SmartSpin_parameters.h
- include/settings.h
- src/BLE_Server.cpp
- src/HTTP_Server_Basic.cpp
- src/SmartSpin_parameters.cpp
Added a HTML button to toggle between automatic HR->PWR. 
Added a BLE scan when user selects save on the select bluetooth devices page.  
Default watts reduced from 100 to 30
> Hr to pwr button

- data/settings.html
Hide the Wifi password by default and provide an option to show it.
See: https://github.com/doudar/SmartSpin2k/issues/87
> Hide Wifi password by default

- include/BLE_Common.h
- src/BLE_Client.cpp
- src/BLE_Common.cpp
Add sensor data abstraction and implement for Heartrate, Flywheel, and FTMS.
TODO: Cadence and Power Sensor Implementation
> Sensor Data Abstraction

- src/HTTP_Server_Basic.cpp
Fix mDNS dropouts by adding a service text record that gets updated every minute.
> Fix mDNS dropouts

- data/index.html
Add in change that got missed in the prior PR
> Fix missing html

- data/settings.html
- src/HTTP_Server_Basic.cpp
Paralleling the develop branch.
> Set hostname for dns

- README.md
Thank you @lenzirodrigo for contributing the Aliexpress shopping list!
> Added Aliexpress Shopping list

- README.md
Edited link to SmartSpin2K programmer so it's not version specific.
> Updated link to the smartspin2k programmer

- data/settings.html
- src/HTTP_Server_Basic.cpp
Reverts doudar/SmartSpin2k#120
> Revert "Set hostname for dns"

- src/BLE_Common.cpp
Forgot adding double power option when the client code was re-written. 
Feel free to merge when you approve - it's a pretty straight forward change.
> Added Double Power

- include/BLE_Common.h
- src/BLE_Server.cpp
> Fitness machine feature enum v2

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- include/BLE_Common.h
- include/sensors/FitnessMachineIndoorBikeData.h
- src/BLE_Client.cpp
- src/BLE_Server.cpp
- src/sensors/FlywheelData.cpp
1. Moves the CHANGELOG.md file parsing to a pre-commit action that can happen locally as well as on GitHub
2. Adds `platformio run` as a final GitHub action to ensure that PRs compile
3. Excludes `Hardware/**` from running the PR github actions
4. Fixes an issue with the FTMS server in which the advertised data didn't match the transmitted data 
5. Fixes a coding error with the FTMS client
> Fix merge issues and add build as github action

- CHANGELOG.md
- data/bluetoothscanner.html
> Power Correction Factor slider now updates correctly

- CHANGELOG.md
- firmware checklist
Checklist to complete for PR and release candidates
> Create firmware checklist

- CHANGELOG.md
- CustomCharacteristic.md
- include/BLE_Common.h
- include/Main.h
- include/SmartSpin_parameters.h
- include/settings.h
- lib/SS2K/include/Constants.h
- src/BLE_Client.cpp
- src/BLE_Common.cpp
- src/BLE_Server.cpp
- src/BLE_Setup.cpp
- src/HTTP_Server_Basic.cpp
- src/Main.cpp
- src/SS2KLog.cpp
- src/SmartSpin_parameters.cpp
- test/native/test_FitnessMachineIndoorBikeData.cpp
Latest Custom Characteristic Updates
> Custom characteristic development

- CHANGELOG.md
- data/btsimulator.html
- data/index.html
- data/settings.html
- data/shift.html
- data/style.css
- include/BLE_Common.h
- include/ERG_Mode.h
- include/Main.h
- include/SS2KLog.h
- include/SmartSpin_parameters.h
- include/settings.h
- platformio.ini
- src/BLE_Client.cpp
- src/BLE_Common.cpp
- src/BLE_Server.cpp
- src/ERG_Mode.cpp
- src/HTTP_Server_Basic.cpp
- src/Main.cpp
- src/SmartSpin_parameters.cpp
- test/native/test.cpp
- test/native/test.h
- test/native/test_PowerBuffer.cpp
> Erg respin!

- CHANGELOG.md
- src/BLE_Client.cpp
Leaving this open as work will be done here to fix the ongoing issues with too much radio time.
> UDP delay and timings

- CHANGELOG.md
- data/status.html
- include/WebsocketAppender.h
- src/WebsocketAppender.cpp
Extended WebsocketsAppender to let multiple clients connect.
All clients will receive all messages sent to appender.
Up to 4 clients can connect.
Status.html will detect connection loss to websockets server and try to reconnect.
> WebSocketAppender can handle multiple client.

- CHANGELOG.md
- include/settings.h
- src/ERG_Mode.cpp
- src/Main.cpp
> Power table bug fix
